-- 01_create_users.sql
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    must_change_password NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT chk_users_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT chk_users_must_change_password CHECK (must_change_password IN (0, 1))
);

COMMENT ON TABLE users IS 'Tabla de usuarios del sistema';
COMMENT ON COLUMN users.enabled IS '1=activo, 0=inactivo';
COMMENT ON COLUMN users.must_change_password IS '1=debe cambiar contraseña, 0=no debe cambiar';


-- 02_create_roles.sql
CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL UNIQUE
);

COMMENT ON TABLE roles IS 'Catálogo de roles del sistema';

-- 03_create_user_roles.sql
CREATE TABLE user_roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_roles UNIQUE (user_id, role_id)
);

CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX idx_user_roles_role_id ON user_roles(role_id);

COMMENT ON TABLE user_roles IS 'Relación muchos a muchos entre usuarios y roles';


-- 04_create_employees.sql
CREATE TABLE employees (
    id_employee NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(255) NOT NULL,
    last_name VARCHAR2(255) NOT NULL,
    employee_code VARCHAR2(255) NOT NULL UNIQUE,
    department VARCHAR2(255),
    position VARCHAR2(255),
    hire_date DATE NOT NULL,
    user_id NUMBER,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    first_login NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_employees_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT chk_employees_first_login CHECK (first_login IN (0, 1))
);

CREATE INDEX idx_employees_user_id ON employees(user_id);
CREATE INDEX idx_employees_employee_code ON employees(employee_code);
CREATE INDEX idx_employees_enabled ON employees(enabled);

COMMENT ON TABLE employees IS 'Tabla de empleados';
COMMENT ON COLUMN employees.enabled IS '1=activo, 0=inactivo';
COMMENT ON COLUMN employees.first_login IS '1=primer inicio de sesión pendiente, 0=ya inició sesión';

-- 05_create_work_schedules.sql
CREATE TABLE work_schedules (
    id_work_schedule NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    day_of_week VARCHAR2(20) NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_work_schedules_employee FOREIGN KEY (employee_id) REFERENCES employees(id_employee) ON DELETE CASCADE,
    CONSTRAINT chk_work_schedules_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT chk_work_schedules_day CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);

CREATE INDEX idx_work_schedules_employee_id ON work_schedules(employee_id);
CREATE INDEX idx_work_schedules_day_enabled ON work_schedules(day_of_week, enabled);

COMMENT ON TABLE work_schedules IS 'Horarios de trabajo de los empleados';
COMMENT ON COLUMN work_schedules.day_of_week IS 'Día de la semana: MONDAY, TUESDAY, etc.';
COMMENT ON COLUMN work_schedules.enabled IS '1=activo, 0=inactivo';

-- 06_create_attendance_records.sql
CREATE TABLE attendance_records (
    id_attendance_record NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    check_in TIMESTAMP,
    check_out TIMESTAMP,
    status VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_attendance_records_employee FOREIGN KEY (employee_id) REFERENCES employees(id_employee) ON DELETE CASCADE,
    CONSTRAINT chk_attendance_records_status CHECK (status IN ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', 'PARTIAL'))
);

CREATE INDEX idx_attendance_records_employee_id ON attendance_records(employee_id);
CREATE INDEX idx_attendance_records_created_at ON attendance_records(created_at);
CREATE INDEX idx_attendance_records_status ON attendance_records(status);
CREATE INDEX idx_attendance_records_emp_created ON attendance_records(employee_id, created_at);

COMMENT ON TABLE attendance_records IS 'Registros de asistencia diaria de empleados';
COMMENT ON COLUMN attendance_records.status IS 'Estado: PRESENT, ABSENT, LATE, EXCUSED, PARTIAL';



-- 07_create_justifications.sql
CREATE TABLE justifications (
    id_justification NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_record_id NUMBER NOT NULL UNIQUE,
    justification_text VARCHAR2(1000),
    submitted_at TIMESTAMP,
    approved NUMBER(1),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_justifications_attendance FOREIGN KEY (attendance_record_id) REFERENCES attendance_records(id_attendance_record) ON DELETE CASCADE,
    CONSTRAINT chk_justifications_approved CHECK (approved IN (0, 1) OR approved IS NULL)
);

CREATE INDEX idx_justifications_attendance_id ON justifications(attendance_record_id);
CREATE INDEX idx_justifications_submitted_at ON justifications(submitted_at);

COMMENT ON TABLE justifications IS 'Justificaciones de ausencias o llegadas tardías';
COMMENT ON COLUMN justifications.justification_text IS 'NULL=pendiente, NOT NULL=completado';
COMMENT ON COLUMN justifications.approved IS '1=aprobado, 0=rechazado, NULL=pendiente de revisión';



CREATE TABLE attendance_record_logs (
    id_log NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_attendance_record NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    employee_code VARCHAR2(50),
    employee_name VARCHAR2(200),
    action_type VARCHAR2(20) NOT NULL,
    old_check_in TIMESTAMP,
    new_check_in TIMESTAMP,
    old_check_out TIMESTAMP,
    new_check_out TIMESTAMP,
    old_status VARCHAR2(50),
    new_status VARCHAR2(50),
    modified_by VARCHAR2(100),
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR2(50),
    user_agent VARCHAR2(500),
    CONSTRAINT fk_log_attendance FOREIGN KEY (id_attendance_record) 
        REFERENCES attendance_records(id_attendance_record) ON DELETE CASCADE,
    CONSTRAINT fk_log_employee FOREIGN KEY (employee_id) 
        REFERENCES employees(id_employee) ON DELETE CASCADE
);

CREATE INDEX idx_log_attendance_record ON attendance_record_logs(id_attendance_record);
CREATE INDEX idx_log_employee ON attendance_record_logs(employee_id);
CREATE INDEX idx_log_modified_at ON attendance_record_logs(modified_at);
CREATE INDEX idx_log_action_type ON attendance_record_logs(action_type);


CREATE TABLE justification_logs (
    id_log NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_justification NUMBER NOT NULL,
    id_attendance_record NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    employee_code VARCHAR2(50),
    employee_name VARCHAR2(200),
    action_type VARCHAR2(20) NOT NULL,
    old_justification_text CLOB,
    new_justification_text CLOB,
    old_submitted_at TIMESTAMP,
    new_submitted_at TIMESTAMP,
    old_approved NUMBER(1),
    new_approved NUMBER(1),
    modified_by VARCHAR2(100),
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR2(50),
    CONSTRAINT fk_jlog_justification FOREIGN KEY (id_justification) 
        REFERENCES justifications(id_justification) ON DELETE CASCADE,
    CONSTRAINT fk_jlog_attendance FOREIGN KEY (id_attendance_record) 
        REFERENCES attendance_records(id_attendance_record) ON DELETE CASCADE,
    CONSTRAINT fk_jlog_employee FOREIGN KEY (employee_id) 
        REFERENCES employees(id_employee) ON DELETE CASCADE
);

CREATE INDEX idx_jlog_justification ON justification_logs(id_justification);
CREATE INDEX idx_jlog_attendance_record ON justification_logs(id_attendance_record);
CREATE INDEX idx_jlog_employee ON justification_logs(employee_id);
CREATE INDEX idx_jlog_modified_at ON justification_logs(modified_at);
CREATE INDEX idx_jlog_action_type ON justification_logs(action_type);